# Generated by Django 5.0 on 2023-12-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
